In [1]:
import time 
import numpy as np 
import pandas as pd 
from IPython.display import display 
from pgmpy.causal_discovery import GES 
from pgmpy.structure_score import get_scoring_method 
from pgmpy.base import PDAG 
from pgmpy.example_models import load_model

c:\Users\Anusa\anaconda3\envs\pgmpy\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def load_bnlearn_dataset(dataset_name, n_samples=5000, seed=42):
    """ Loads and simulates a bnlearn dataset. """ 
    model = load_model( f"bnlearn/{dataset_name}" ) 
    data = model.simulate(n_samples=n_samples, seed=seed) 
    return data.astype("category")

In [3]:
def compute_graph_score(model, scoring_method, data): 
    """ Computes total graph score. """ 
    score = get_scoring_method(scoring_method, data) 
    score_fn = score.local_score 
    if isinstance(model, PDAG): 
        model = model.to_dag() 
    total_score = 0 
    for node in model.nodes(): 
        parents = tuple(model.predecessors(node)) 
        total_score += score_fn(node, parents) 
    return total_score

In [4]:
def benchmark_grid(data, scoring_method, dataset_name): 
    n_jobs_values = [1, 2, 4, 8, 16] 
    max_parent_values = [1, 2, 4, 8, 16] 
    results = [] 
    print("\n" + "=" * 80) 
    print(f"Running benchmark for: {dataset_name}") 
    print("=" * 80) 
    for n_jobs in n_jobs_values: 
        for max_parents in max_parent_values: 
            print( f"Running " f"n_jobs={n_jobs}, " f"max_parents={max_parents}" ) 
            start = time.perf_counter() 
            est = GES(variant="fges", scoring_method=scoring_method, n_jobs=n_jobs, max_parents=max_parents) 
            est.fit(data) 
            runtime = (time.perf_counter() - start) 
            graph_score = compute_graph_score(est.causal_graph_, scoring_method, data) 
            results.append({"dataset": dataset_name, "n_jobs": n_jobs, "max_parents": max_parents, "runtime_sec": round(runtime, 4), "graph_score": round(graph_score, 4), "num_edges": len( est.causal_graph_.edges()),}) 
        results_df = pd.DataFrame(results)
         
    return results_df

In [5]:
datasets = [ "sachs", "child", "alarm", "asia", "cancer"] 
all_results = [] 
for dataset_name in datasets: 
    data = load_bnlearn_dataset(dataset_name, n_samples=5000, seed=42) 
    results_df = benchmark_grid(data=data, scoring_method="bic-d", dataset_name=dataset_name.capitalize()) 
    all_results.append(results_df) 
    print( f"\nBenchmark Results: " f"{dataset_name.upper()}" ) 
    display(results_df)

D:\pgmpy\pgmpy\pgmpy\estimators\__init__.py:4: FutureWarning: `pgmpy.estimators.StructureScore` is deprecated and will be removed in v1.3.0. Use `pgmpy.structure_score` instead.
  from .StructureScore import (
Generating for node: Akt: 100%|██████████| 11/11 [00:00<00:00, 14.08it/s]

================================================================================
Running benchmark for: Sachs
================================================================================
Running n_jobs=1, max_parents=1
Running n_jobs=1, max_parents=2
Running n_jobs=1, max_parents=4
Running n_jobs=1, max_parents=8
Running n_jobs=1, max_parents=16
Running n_jobs=2, max_parents=1
Running n_jobs=2, max_parents=2
Running n_jobs=2, max_parents=4
Running n_jobs=2, max_parents=8
Running n_jobs=2, max_parents=16
Running n_jobs=4, max_parents=1
Running n_jobs=4, max_parents=2
Running n_jobs=4, max_parents=4
Running n_jobs=4, max_parents=8
Running n_jobs=4, max_parents=16
Running n_jobs=8, max_parents=1
Running n_jobs=8, max_parents=2
Running n_jobs=8, max_parents=4
Running n_jobs=8, max_parents=8
Running n_jobs=8, max_parents=16
Running n_jobs=16, max_parents=1
Running n_jobs=16, max_parents=2
Running n_jobs=16, max_parents=4
Running n_jobs=16, max_parents=8
Running n_jobs=16, max_parents=16

Benchmark Results: SACHS

   dataset  n_jobs  max_parents  runtime_sec  graph_score  num_edges
0    Sachs       1            1       0.2185  -39427.0602         14
1    Sachs       1            2       0.3582  -37834.9325         26
2    Sachs       1            4       0.4728  -37611.7686         28
3    Sachs       1            8       0.4690  -37611.7686         28
4    Sachs       1           16       0.4707  -37611.7686         28
5    Sachs       2            1       0.4276  -39427.0602         14
6    Sachs       2            2       1.2155  -37834.9325         26
7    Sachs       2            4       1.6817  -37611.7686         28
8    Sachs       2            8       1.0265  -37611.7686         28
9    Sachs       2           16       1.3286  -37611.7686         28
10   Sachs       4            1       0.4083  -39427.0602         14
11   Sachs       4            2       0.9957  -37834.9325         26
12   Sachs       4            4       0.9376  -37611.7686         28
13   Sachs       4            8       1.0301  -37611.7686         28
14   Sachs       4           16       1.1862  -37611.7686         28
15   Sachs       8            1       0.4976  -39427.0602         14
16   Sachs       8            2       0.7628  -37834.9325         26
17   Sachs       8            4       1.1510  -37611.7686         28
18   Sachs       8            8       0.9911  -37611.7686         28
19   Sachs       8           16       1.4120  -37611.7686         28
20   Sachs      16            1       0.7489  -39427.0602         14
21   Sachs      16            2       1.5834  -37834.9325         26
22   Sachs      16            4       1.1819  -37611.7686         28
23   Sachs      16            8       1.6072  -37611.7686         28
24   Sachs      16           16       1.1210  -37611.7686         28

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Generating for node: GruntingReport: 100%|██████████| 20/20 [00:00<00:00, 88.05it/s]

================================================================================
Running benchmark for: Child
================================================================================
Running n_jobs=1, max_parents=1
Running n_jobs=1, max_parents=2
Running n_jobs=1, max_parents=4
Running n_jobs=1, max_parents=8
Running n_jobs=1, max_parents=16
Running n_jobs=2, max_parents=1
Running n_jobs=2, max_parents=2
Running n_jobs=2, max_parents=4
Running n_jobs=2, max_parents=8
Running n_jobs=2, max_parents=16
Running n_jobs=4, max_parents=1
Running n_jobs=4, max_parents=2
Running n_jobs=4, max_parents=4
Running n_jobs=4, max_parents=8
Running n_jobs=4, max_parents=16
Running n_jobs=8, max_parents=1
Running n_jobs=8, max_parents=2
Running n_jobs=8, max_parents=4
Running n_jobs=8, max_parents=8
Running n_jobs=8, max_parents=16
Running n_jobs=16, max_parents=1
Running n_jobs=16, max_parents=2
Running n_jobs=16, max_parents=4
Running n_jobs=16, max_parents=8
Running n_jobs=16, max_parents=16

Benchmark Results: CHILD

   dataset  n_jobs  max_parents  runtime_sec  graph_score  num_edges
0    Child       1            1       3.0309  -63397.4405         38
1    Child       1            2       2.6410  -61452.0972         36
2    Child       1            4       2.7075  -61452.0972         36
3    Child       1            8       2.7462  -61452.0972         36
4    Child       1           16       3.1729  -61452.0972         36
5    Child       2            1       3.4971  -63397.4405         38
6    Child       2            2       9.0997  -61452.0972         36
7    Child       2            4       6.2470  -61452.0972         36
8    Child       2            8       8.9620  -61452.0972         36
9    Child       2           16       8.8121  -61452.0972         36
10   Child       4            1       7.1051  -63397.4405         38
11   Child       4            2       9.6054  -61452.0972         36
12   Child       4            4      14.5587  -61452.0972         36
13   Child       4            8      15.4436  -61452.0972         36
14   Child       4           16      17.4539  -61452.0972         36
15   Child       8            1       4.6108  -63397.4405         38
16   Child       8            2       6.5272  -61452.0972         36
17   Child       8            4       3.7660  -61452.0972         36
18   Child       8            8       3.8258  -61452.0972         36
19   Child       8           16      10.9379  -61452.0972         36
20   Child      16            1      12.4374  -63397.4405         38
21   Child      16            2      15.0132  -61452.0972         36
22   Child      16            4      14.1753  -61452.0972         36
23   Child      16            8       8.7802  -61452.0972         36
24   Child      16           16      14.4970  -61452.0972         36

Generating for node: BP: 100%|██████████| 37/37 [00:00<00:00, 113.81it/s]

================================================================================
Running benchmark for: Alarm
================================================================================
Running n_jobs=1, max_parents=1
Running n_jobs=1, max_parents=2
Running n_jobs=1, max_parents=4
Running n_jobs=1, max_parents=8
Running n_jobs=1, max_parents=16
Running n_jobs=2, max_parents=1
Running n_jobs=2, max_parents=2
Running n_jobs=2, max_parents=4
Running n_jobs=2, max_parents=8
Running n_jobs=2, max_parents=16
Running n_jobs=4, max_parents=1
Running n_jobs=4, max_parents=2
Running n_jobs=4, max_parents=4
Running n_jobs=4, max_parents=8
Running n_jobs=4, max_parents=16
Running n_jobs=8, max_parents=1
Running n_jobs=8, max_parents=2
Running n_jobs=8, max_parents=4
Running n_jobs=8, max_parents=8
Running n_jobs=8, max_parents=16
Running n_jobs=16, max_parents=1
Running n_jobs=16, max_parents=2
Running n_jobs=16, max_parents=4
Running n_jobs=16, max_parents=8
Running n_jobs=16, max_parents=16

Benchmark Results: ALARM

   dataset  n_jobs  max_parents  runtime_sec  graph_score  num_edges
0    Alarm       1            1      10.9342  -58682.6027         35
1    Alarm       1            2       8.7287  -54656.4417         45
2    Alarm       1            4       8.8369  -54656.4417         45
3    Alarm       1            8      11.2079  -54656.4417         45
4    Alarm       1           16       8.8472  -54656.4417         45
5    Alarm       2            1      11.9983  -58682.6027         35
6    Alarm       2            2      12.2159  -54656.4417         45
7    Alarm       2            4      12.2415  -54656.4417         45
8    Alarm       2            8      12.9214  -54656.4417         45
9    Alarm       2           16      12.3018  -54656.4417         45
10   Alarm       4            1      11.9470  -58682.6027         35
11   Alarm       4            2      14.2946  -54656.4417         45
12   Alarm       4            4      11.7124  -54656.4417         45
13   Alarm       4            8      18.9466  -54656.4417         45
14   Alarm       4           16      12.1121  -54656.4417         45
15   Alarm       8            1      11.2943  -58682.6027         35
16   Alarm       8            2      10.6459  -54656.4417         45
17   Alarm       8            4      11.4606  -54656.4417         45
18   Alarm       8            8      13.6242  -54656.4417         45
19   Alarm       8           16      12.4074  -54656.4417         45
20   Alarm      16            1      12.3664  -58682.6027         35
21   Alarm      16            2      17.7473  -54656.4417         45
22   Alarm      16            4      14.4789  -54656.4417         45
23   Alarm      16            8      11.8262  -54656.4417         45
24   Alarm      16           16      11.5171  -54656.4417         45

Generating for node: dysp: 100%|██████████| 8/8 [00:00<00:00, 247.81it/s]

================================================================================
Running benchmark for: Asia
================================================================================
Running n_jobs=1, max_parents=1
Running n_jobs=1, max_parents=2
Running n_jobs=1, max_parents=4
Running n_jobs=1, max_parents=8
Running n_jobs=1, max_parents=16
Running n_jobs=2, max_parents=1
Running n_jobs=2, max_parents=2
Running n_jobs=2, max_parents=4
Running n_jobs=2, max_parents=8
Running n_jobs=2, max_parents=16
Running n_jobs=4, max_parents=1
Running n_jobs=4, max_parents=2
Running n_jobs=4, max_parents=4
Running n_jobs=4, max_parents=8
Running n_jobs=4, max_parents=16
Running n_jobs=8, max_parents=1
Running n_jobs=8, max_parents=2
Running n_jobs=8, max_parents=4
Running n_jobs=8, max_parents=8
Running n_jobs=8, max_parents=16
Running n_jobs=16, max_parents=1
Running n_jobs=16, max_parents=2
Running n_jobs=16, max_parents=4
Running n_jobs=16, max_parents=8
Running n_jobs=16, max_parents=16

Benchmark Results: ASIA

   dataset  n_jobs  max_parents  runtime_sec  graph_score  num_edges
0     Asia       1            1       0.1161  -11280.2552          7
1     Asia       1            2       0.1108  -11189.0062          9
2     Asia       1            4       0.1002  -11189.0062          9
3     Asia       1            8       0.1026  -11189.0062          9
4     Asia       1           16       0.1593  -11189.0062          9
5     Asia       2            1       0.4278  -11280.2552          7
6     Asia       2            2       0.5615  -11189.0062          9
7     Asia       2            4       0.5996  -11189.0062          9
8     Asia       2            8       0.5712  -11189.0062          9
9     Asia       2           16       0.6243  -11189.0062          9
10    Asia       4            1       0.4849  -11280.2552          7
11    Asia       4            2       0.4337  -11189.0062          9
12    Asia       4            4       0.5234  -11189.0062          9
13    Asia       4            8       0.6103  -11189.0062          9
14    Asia       4           16       0.6075  -11189.0062          9
15    Asia       8            1       0.4208  -11280.2552          7
16    Asia       8            2       0.4868  -11189.0062          9
17    Asia       8            4       0.5243  -11189.0062          9
18    Asia       8            8       0.6676  -11189.0062          9
19    Asia       8           16       0.4882  -11189.0062          9
20    Asia      16            1       0.7331  -11280.2552          7
21    Asia      16            2       0.7578  -11189.0062          9
22    Asia      16            4       0.6789  -11189.0062          9
23    Asia      16            8       0.7445  -11189.0062          9
24    Asia      16           16       0.7458  -11189.0062          9

Generating for node: Dyspnoea: 100%|██████████| 5/5 [00:00<00:00, 197.62it/s]

================================================================================
Running benchmark for: Cancer
================================================================================
Running n_jobs=1, max_parents=1
Running n_jobs=1, max_parents=2
Running n_jobs=1, max_parents=4
Running n_jobs=1, max_parents=8
Running n_jobs=1, max_parents=16
Running n_jobs=2, max_parents=1
Running n_jobs=2, max_parents=2
Running n_jobs=2, max_parents=4
Running n_jobs=2, max_parents=8
Running n_jobs=2, max_parents=16
Running n_jobs=4, max_parents=1
Running n_jobs=4, max_parents=2
Running n_jobs=4, max_parents=4
Running n_jobs=4, max_parents=8
Running n_jobs=4, max_parents=16
Running n_jobs=8, max_parents=1
Running n_jobs=8, max_parents=2
Running n_jobs=8, max_parents=4
Running n_jobs=8, max_parents=8
Running n_jobs=8, max_parents=16
Running n_jobs=16, max_parents=1
Running n_jobs=16, max_parents=2
Running n_jobs=16, max_parents=4
Running n_jobs=16, max_parents=8
Running n_jobs=16, max_parents=16

Benchmark Results: CANCER

   dataset  n_jobs  max_parents  runtime_sec  graph_score  num_edges
0   Cancer       1            1       0.0386   -10390.329          6
1   Cancer       1            2       0.0478   -10390.329          6
2   Cancer       1            4       0.0408   -10390.329          6
3   Cancer       1            8       0.0442   -10390.329          6
4   Cancer       1           16       0.0719   -10390.329          6
5   Cancer       2            1       0.1672   -10390.329          6
6   Cancer       2            2       0.2482   -10390.329          6
7   Cancer       2            4       0.1769   -10390.329          6
8   Cancer       2            8       0.1594   -10390.329          6
9   Cancer       2           16       0.1799   -10390.329          6
10  Cancer       4            1       0.1747   -10390.329          6
11  Cancer       4            2       0.1590   -10390.329          6
12  Cancer       4            4       0.1489   -10390.329          6
13  Cancer       4            8       0.1355   -10390.329          6
14  Cancer       4           16       0.1415   -10390.329          6
15  Cancer       8            1       0.2324   -10390.329          6
16  Cancer       8            2       0.2507   -10390.329          6
17  Cancer       8            4       0.2340   -10390.329          6
18  Cancer       8            8       0.2333   -10390.329          6
19  Cancer       8           16       0.1972   -10390.329          6
20  Cancer      16            1       0.2941   -10390.329          6
21  Cancer      16            2       0.2244   -10390.329          6
22  Cancer      16            4       0.2133   -10390.329          6
23  Cancer      16            8       0.2709   -10390.329          6
24  Cancer      16           16       0.2228   -10390.329          6

In [6]:
def benchmark_plain_ges(
    data,
    scoring_method,
    dataset_name,
):
    results = []
    print("\n" + "=" * 80)
    print(
        f"Running baseline GES for: "
        f"{dataset_name}"
    )
    print("=" * 80)
    start = time.perf_counter()
    est = GES(scoring_method=scoring_method)
    est.fit(data)
    runtime = time.perf_counter() - start
    graph_score = compute_graph_score(est.causal_graph_, scoring_method, data)
    results.append(
        {
            "dataset": dataset_name,
            "runtime_sec": round(runtime, 4),
            "graph_score": round(graph_score, 4),
            "num_edges": len(
                est.causal_graph_.edges()
            ),
        }
    )

    results_df = pd.DataFrame(results)

    return results_df

In [7]:
datasets = [ "sachs", "child", "alarm", "asia", "cancer"] 
all_results = [] 
for dataset_name in datasets: 
    data = load_bnlearn_dataset(dataset_name, n_samples=5000, seed=42) 
    results_df = benchmark_plain_ges(data=data, scoring_method="bic-d", dataset_name=dataset_name.capitalize()) 
    all_results.append(results_df) 
    print( f"\nBenchmark Results: " f"{dataset_name.upper()}" ) 
    display(results_df)

Generating for node: Akt: 100%|██████████| 11/11 [00:00<00:00, 112.96it/s]

================================================================================
Running baseline GES for: Sachs
================================================================================

Benchmark Results: SACHS

  dataset  runtime_sec  graph_score  num_edges
0   Sachs       0.7662  -36278.1836         34

Generating for node: GruntingReport: 100%|██████████| 20/20 [00:00<00:00, 92.13it/s]

================================================================================
Running baseline GES for: Child
================================================================================

Benchmark Results: CHILD

  dataset  runtime_sec  graph_score  num_edges
0   Child       4.2375  -61410.1058         37

Generating for node: BP: 100%|██████████| 37/37 [00:00<00:00, 156.55it/s]

================================================================================
Running baseline GES for: Alarm
================================================================================

Benchmark Results: ALARM

  dataset  runtime_sec  graph_score  num_edges
0   Alarm       32.991  -53715.8562         49

Generating for node: dysp: 100%|██████████| 8/8 [00:00<00:00, 126.45it/s]

================================================================================
Running baseline GES for: Asia
================================================================================

Benchmark Results: ASIA

  dataset  runtime_sec  graph_score  num_edges
0    Asia       0.2197  -11189.0062          9

Generating for node: Dyspnoea: 100%|██████████| 5/5 [00:00<00:00, 170.31it/s]

================================================================================
Running baseline GES for: Cancer
================================================================================

Benchmark Results: CANCER

  dataset  runtime_sec  graph_score  num_edges
0  Cancer        0.045   -10390.329          6